name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      
      - name: Build WASM (Release)
        run: cargo build --release --target wasm32-unknown-unknown
      
      - name: Verify WASM file
        run: |
          ls -lh target/wasm32-unknown-unknown/release/dprint_plugin_tailwindcss.wasm
          file target/wasm32-unknown-unknown/release/dprint_plugin_tailwindcss.wasm
      
      - name: Create plugin info JSON
        run: |
          cat > plugin-info.json << 'EOF'
          {
            "schemaVersion": 4,
            "name": "dprint-plugin-tailwindcss",
            "version": "${{ steps.get_version.outputs.version }}",
            "linux-x86_64": {
              "reference": "https://github.com/friedjoff/dprint-plugin-tailwindcss/releases/download/v${{ steps.get_version.outputs.version }}/dprint_plugin_tailwindcss.wasm",
              "checksum": ""
            },
            "mac-x86_64": {
              "reference": "https://github.com/friedjoff/dprint-plugin-tailwindcss/releases/download/v${{ steps.get_version.outputs.version }}/dprint_plugin_tailwindcss.wasm",
              "checksum": ""
            },
            "mac-aarch64": {
              "reference": "https://github.com/friedjoff/dprint-plugin-tailwindcss/releases/download/v${{ steps.get_version.outputs.version }}/dprint_plugin_tailwindcss.wasm",
              "checksum": ""
            },
            "windows-x86_64": {
              "reference": "https://github.com/friedjoff/dprint-plugin-tailwindcss/releases/download/v${{ steps.get_version.outputs.version }}/dprint_plugin_tailwindcss.wasm",
              "checksum": ""
            }
          }
          EOF
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/wasm32-unknown-unknown/release/dprint_plugin_tailwindcss.wasm
            plugin-info.json
          body: |
            ## dprint-plugin-tailwindcss ${{ steps.get_version.outputs.version }}
            
            ### Installation
            
            Add to your `dprint.json`:
            ```json
            {
              "plugins": [
                "https://github.com/friedjoff/dprint-plugin-tailwindcss/releases/download/${{ github.ref_name }}/dprint_plugin_tailwindcss.wasm"
              ]
            }
            ```
            
            ### Changes
            
            See [CHANGELOG.md](https://github.com/friedjoff/dprint-plugin-tailwindcss/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false
